entity: StockItem
key: InventoryID
records:
- InventoryID: RAW-ECH-EXT4
  Description: Organic Echinacea extract 4% polyphenols
  ItemClass: PARTS
  ItemStatus: Active
  DefaultWarehouseID: WH-MISS-01
  LotSerialClass: LOTRAW
- InventoryID: RAW-ELD-EXT10
  Description: Organic elderberry extract 10% anthocyanins
  ItemClass: PARTS
  ItemStatus: Active
  DefaultWarehouseID: WH-MISS-01
  LotSerialClass: LOTRAW
- InventoryID: RAW-ASH-EXT5
  Description: Organic ashwagandha extract 5% withanolides
  ItemClass: PARTS
  ItemStatus: Active
  DefaultWarehouseID: WH-MISS-01
  LotSerialClass: LOTRAW
- InventoryID: RAW-COQ10-99
  Description: Coenzyme Q10 USP 99%
  ItemClass: PARTS
  ItemStatus: Active
  DefaultWarehouseID: WH-MISS-01
  LotSerialClass: LOTRAW
- InventoryID: RAW-OMEGA3-70
  Description: Marine omega-3 TG oil 70% EPA/DHA
  ItemClass: PARTS
  ItemStatus: Active
  DefaultWarehouseID: WH-MISS-01
  LotSerialClass: LOTRAW
- InventoryID: RAW-ASTA-10
  Description: Natural astaxanthin oleoresin 10%
  ItemClass: PARTS
  ItemStatus: Active
  DefaultWarehouseID: WH-MISS-01
  LotSerialClass: LOTRAW
