entity: KitSpecification
key: [KitInventoryID, RevisionID]
detail_keys:
  StockComponents: StockInventoryID
records:
- KitInventoryID: GW-EDGE
  RevisionID: V1
  Description: Edge IoT Gateway bill of components
  Active: true
  StockComponents:
  - StockInventoryID: ENCL-STD
    ComponentQty: 1
    UOM: EA
  - StockInventoryID: MB-CM4
    ComponentQty: 1
    UOM: EA
  - StockInventoryID: ANT-LORA
    ComponentQty: 1
    UOM: EA
  - StockInventoryID: PSU-12V
    ComponentQty: 1
    UOM: EA
  - StockInventoryID: SD-32GB
    ComponentQty: 1
    UOM: EA
  - StockInventoryID: CBL-PWR
    ComponentQty: 1
    UOM: EA
- KitInventoryID: GW-CELL
  RevisionID: V1
  Description: Cellular IoT Gateway bill of components
  Active: true
  StockComponents:
  - StockInventoryID: ENCL-STD
    ComponentQty: 1
    UOM: EA
  - StockInventoryID: MB-CM4
    ComponentQty: 1
    UOM: EA
  - StockInventoryID: MOD-LTE
    ComponentQty: 1
    UOM: EA
  - StockInventoryID: ANT-LTE
    ComponentQty: 1
    UOM: EA
  - StockInventoryID: ANT-LORA
    ComponentQty: 1
    UOM: EA
  - StockInventoryID: PSU-12V
    ComponentQty: 1
    UOM: EA
  - StockInventoryID: SD-32GB
    ComponentQty: 1
    UOM: EA
  - StockInventoryID: CBL-PWR
    ComponentQty: 1
    UOM: EA
- KitInventoryID: GW-RAIL
  RevisionID: V1
  Description: DIN-Rail Industrial Gateway bill of components
  Active: true
  StockComponents:
  - StockInventoryID: ENCL-DIN
    ComponentQty: 1
    UOM: EA
  - StockInventoryID: MB-CM4
    ComponentQty: 1
    UOM: EA
  - StockInventoryID: ANT-LORA
    ComponentQty: 1
    UOM: EA
  - StockInventoryID: PSU-12V
    ComponentQty: 1
    UOM: EA
  - StockInventoryID: SD-32GB
    ComponentQty: 1
    UOM: EA
  - StockInventoryID: CBL-PWR
    ComponentQty: 1
    UOM: EA
